import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "../contexts/AppContext";
import { Roboto, Poppins } from 'next/font/google';

    const roboto = Roboto({
      weight: '400', // Or use variable fonts for better performance
      subsets: ['latin'],
      variable: '--font-roboto', // Optional: Define a CSS variable
    });
    const poppins = Roboto({
      weight: '400', // Or use variable fonts for better performance
      subsets: ['latin'],
      variable: '--font-poppins', // Optional: Define a CSS variable
    });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${poppins.className} ${roboto.className}`}
      >
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
